language: php

dist: trusty

php:
  - 7.1
  - 7.2
  - 7.3
  - hhvm
  - nightly

env:
  - ILLUMINATE_VERSION=5.1.*
  - PHPUNIT_REQUIRED=1
  
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - composer self-update
  - composer require "illuminate/support:${ILLUMINATE_VERSION}" --no-update
  - if [[ $PHPUNIT_REQUIRED == "1" ]]; then composer require "phpunit/phpunit"; fi
  - composer install --prefer-source --no-interaction

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && $TRAVIS_PHP_VERSION != "hhvm" && $TRAVIS_PHP_VERSION != "nightly" && $TRAVIS_PHP_VERSION != "7.3" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi

matrix:
  include:
    - php: 7.1
      env: ILLUMINATE_VERSION=5.2.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.3.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.4.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.5.* PHPUNIT_REQUIRED=0
    - php: 7.1
      env: ILLUMINATE_VERSION=5.6.* PHPUNIT_REQUIRED=0
    - php: 7.2
      env: ILLUMINATE_VERSION=5.2.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.3.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.4.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.5.* PHPUNIT_REQUIRED=0
    - php: 7.2
      env: ILLUMINATE_VERSION=5.6.* PHPUNIT_REQUIRED=0
    - php: 7.3
      env: ILLUMINATE_VERSION=5.2.*
    - php: 7.3
      env: ILLUMINATE_VERSION=5.3.*
    - php: 7.3
      env: ILLUMINATE_VERSION=5.4.*
    - php: 7.3
      env: ILLUMINATE_VERSION=5.5.* PHPUNIT_REQUIRED=0
    - php: 7.3
      env: ILLUMINATE_VERSION=5.6.* PHPUNIT_REQUIRED=0
    - php: nightly
      env: ILLUMINATE_VERSION=5.2.*
    - php: nightly
      env: ILLUMINATE_VERSION=5.3.*
    - php: nightly
      env: ILLUMINATE_VERSION=5.4.*
    - php: nightly
      env: ILLUMINATE_VERSION=5.5.* PHPUNIT_REQUIRED=0
    - php: nightly
      env: ILLUMINATE_VERSION=5.6.* PHPUNIT_REQUIRED=0
  allow_failures:
    - php: 7.3
    - php: hhvm
    - php: nightly
  fast_finish: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/42a0b0047b8d64beff4c
    on_success: change
    on_failure: always
    on_start: never
